name: migue_iphones
description: "Web para cat√°logo de iPhones y accesorios."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.8.0
  go_router: ^14.6.1
  http: ^1.2.2
  intl: ^0.20.2
  lottie: ^3.3.1
  riverpod_annotation: ^2.5.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  supabase_flutter: ^2.8.1
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.5.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/animations/
    - assets/images/
